AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  go-aws-sam
  
  Sample SAM Template for go-aws-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: go1.x
    Handler: handler-bin
    Architectures:
      - x86_64
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: local
        AWS_SECRET_ACCESS_KEY: local
        AWS_ENDPOINT: http://host.docker.internal:4566

Resources:
  PutMessageApi:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ./lambda/put-message-api
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/put-message
            Method: POST
  PutMessage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda/put-message
  PopMessage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./lambda/pop-message
      Events:
        SqsEvents:
          Type: SQS
          Properties:
            Queue: "MyQueue"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PutMessageApiAPI:
    Description: "API Gateway endpoint URL for Prod environment for PutMessageApi Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lambda/"
  PutMessageApi:
    Description: "PutMessageApi Lambda Function ARN"
    Value: !GetAtt PutMessageApi.Arn
  PutMessageApiIamRole:
    Description: "Implicit IAM Role created for PutMessageApi function"
    Value: !GetAtt PutMessageApiRole.Arn
