AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  put-message
  
  Sample SAM Template for put-message

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  PutMessageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/
      Handler: handler
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: POST
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: local
          AWS_SECRET_ACCESS_KEY: local
          AWS_ENDPOINT: http://localhost:4566
          AWS_ENDPOINT_DOCKER: http://host.docker.internal:4566

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PutMessageAPI:
    Description: "API Gateway endpoint URL for Prod environment for PutMessage Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lambda/"
  PutMessage:
    Description: "PutMessage Lambda Function ARN"
    Value: !GetAtt PutMessage.Arn
  PutMessageIamRole:
    Description: "Implicit IAM Role created for PutMessage function"
    Value: !GetAtt PutMessageRole.Arn
